### ISSUE TITLE
Project stuck at Syncing with LD 99%

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/web-languageforge#1769]
The project Bolinao in Language Forge is stuck on my machine.

![Image](https://user-images.githubusercontent.com/4575355/260923120-fdcbd942-0352-4636-a771-966c3d893976.png)

**Comment by rmunn** [comment]
I found the following in the lfmerge logs:

```plaintext
2023-08-16T02:29:09.0162047Z 33089 - LcmToMongo: Created LfEntry ffff0dce-d65f-43bb-a4cd-d6c38b170873 (sititinek)
2023-08-16T07:35:52.5174519Z Got exception. State going to IDLE
2023-08-16T07:35:52.5315283Z LfMerge exiting due to System.OutOfMemoryException exception in Action.TransferLcmToMongo (Exception of type 'System.OutOfMemoryException' was thrown.)
2023-08-16T07:35:52.5674380Z Got System.OutOfMemoryException exception trying to clone smk-flex: Exception of type 'System.OutOfMemoryException' was thrown.
2023-08-16T07:35:52.5675143Z Got exception. State going to IDLE
2023-08-16T07:35:52.5801861Z LfMerge exiting due to System.OutOfMemoryException exception in Action.EnsureClone (Exception of type 'System.OutOfMemoryException' was thrown.)
2023-08-16T07:35:52.5818437Z Got exception System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at LfMergeBridge.LanguageForgeGetChorusNotesActionHandler.LibTriboroughBridgeChorusPlugin.Infrastructure.IBridgeActionTypeHandler.StartWorking(IProgress progress, Dictionary`2 options, String& somethingForClient)
   at LfMergeBridge.LfMergeBridge.Execute(String actionType, IProgress progress, Dictionary`2 options, String& somethingForClient)
   at LfMerge.Core.DataConverters.ConvertLcmToMongoComments.CallLfMergeBridge(String bridgeInput, String& bridgeOutput) in /home/builder/repo/src/LfMerge.Core/DataConverters/ConvertLcmToMongoComments.cs:line 304
   at LfMerge.Core.DataConverters.ConvertLcmToMongoComments.RunConversion() in /home/builder/repo/src/LfMerge.Core/DataConverters/ConvertLcmToMongoComments.cs:line 49
   at LfMerge.Core.DataConverters.ConvertLcmToMongoLexicon.RunConversion() in /home/builder/repo/src/LfMerge.Core/DataConverters/ConvertLcmToMongoLexicon.cs:line 157
   at LfMerge.Core.Actions.TransferLcmToMongoAction.DoRun(ILfProject project) in /home/builder/repo/src/LfMerge.Core/Actions/TransferLcmToMongoAction.cs:line 68
   at LfMerge.Core.Actions.Action.Run(ILfProject project) in /home/builder/repo/src/LfMerge.Core/Actions/Action.cs:line 110
   at LfMerge.Core.Actions.EnsureCloneAction.InitialTransferToMongoAfterClone(ILfProject project) in /home/builder/repo/src/LfMerge.Core/Actions/EnsureCloneAction.cs:line 72
   at LfMerge.Core.Actions.EnsureCloneAction.DoRun(ILfProject project) in /home/builder/repo/src/LfMerge.Core/Actions/EnsureCloneAction.cs:line 190
   at LfMerge.Core.Actions.Action.Run(ILfProject project) in /home/builder/repo/src/LfMerge.Core/Actions/Action.cs:line 110
   at LfMerge.Program.RunAction(String projectCode, ActionNames currentAction) in /home/builder/repo/src/LfMerge/Program.cs:line 110
```

Haven't yet tracked down which piece of JSON caused the .NET process to run out of memory, but it's something from the ChorusNotes handler in FLExBridge. Which is odd, because ChorusNotes uses XML, not JSON — but I'll investigate further later on.

**Comment by rmunn** [comment]
The JSON in question is the Mongo version of the .ChorusNotes XML file. The code that was running out of memory was the following:

```cs
var serializedComments = new StringBuilder("New comments not yet in LF: ");
serializedComments.Append(JsonConvert.SerializeObject(lfComments));
LfMergeBridgeUtilities.AppendLineToSomethingForClient(ref somethingForClient, serializedComments.ToString());
```

The .ChorusNotes XML file had 26,553 `annotation` elements, each of which turns into a single `lfComment`, so the `lfComments` list being serialized had 26,553 entries in it. Coming on top of converting about 33,000 dictionary entries (which, I suspect but can't prove, were still resident in memory when the comment conversion ran), this made the lfmerge container exhaust the 2.5GiB of maximum RAM it was allowed.

If I'm right that the dictionary entries were still in memory when the comment conversion ran, then re-running the Send/Receive process a second time should work, because the second run won't need to convert those 33,000 dictionary entries this time and so a lot more total RAM will be available for use by the comment conversion.

**Comment by hahn-kev** [comment]
tested this project out and it's working now!
