### ISSUE TITLE
implement a persistent volume for project assets and test that it functions on QA

### ISSUE THREAD

**Issue by megahirt** [sillsdev/web-languageforge#965]
volume mount for app container:
/var/www/html/assets
?? GB

- [x] determine volume size
- [x] implement locally
- [x] update app deployment yml
- [x] utilize app-assets instead of "user" naming

**Comment by longrunningprocess** [comment]
based on our last conversation, I'm going to start with 5GB on the volume size knowing we can grow it if needed.

**Comment by longrunningprocess** [comment]
notes for myself as I'm learning the app:

I spun the app up locally and created a non-send/receive project...

I created a new word and showed the "extra fields" and found an "+ Add Picture" button.  I was able to upload an image there.  I `exec`'d into the `app` container and found my image here: `/var/www/html/assets/lexicon/sf_test_for_project_assets/pictures/20210609183305_you-da-man.jpg`

**Comment by longrunningprocess** [comment]
🐛 

volume looks right and binding to `app` container looks right but I'm getting the following error when trying to upload a picture:
```
[Wed Jun 09 19:43:55.215389 2021] [php7:notice] [pid 27] [client 10.42.1.0:36154] Error in createAllFolders(/var/www/html/assets/lexicon/sf_test_project_assets)\nmkdir(): Permission denied\nParent folder: /var/www/html/assets\nOwner of parent folder: root\nGroup of parent folder: root\nPermissions on parent folder: 755\nPHP running as user: www-data\ndumping all vars: Array\n\n#0 [internal function]: Palaso\\Utilities\\FileUtilities::Palaso\\Utilities\\{closure}(2, 'mkdir(): Permis...', '/var/www/html/v...', 61, Array)\n#1 /var/www/html/vendor/sillsdev/web-php-utilities/src/FileUtilities.php(61): mkdir('/var/www/html/a...', 511, true)\n#2 /var/www/html/Api/Model/Shared/ProjectModel.php(475): Palaso\\Utilities\\FileUtilities::createAllFolders('/var/www/html/a...')\n#3 /var/www/html/Api/Model/Languageforge/Lexicon/LexProjectModel.php(137): Api\\Model\\Shared\\ProjectModel->getAssetsFolderPath()\n#4 /var/www/html/Api/Model/Languageforge/Lexicon/LexProjectModel.php(153): Api\\Model\\Languageforge\\Lexicon\\LexProjectModel->getImageFolderPath()\n#5 /var/www/html/Api/Model/Languageforge/Lexicon/Command/LexUploadCommands.php(168): Api\\Model\\Languageforge\\Lexicon\\LexProjectModel->createAssetsFolders()\n#6 /var/www/html/Api/Service/Sf.php(625): Api\\Model\\Languageforge\\Lexicon\\Command\\LexUploadCommands::uploadImageFile('60c114a487396d7...', 'sense-image', '/tmp/upload_60c...')\n#7 /var/www/html/Site/Controller/Upload.php(59): Api\\Service\\Sf->lex_uploadImageFile('sense-image', '/tmp/upload_60c...')\n#8 [internal function]: Site\\Controller\\Upload->receive(Object(Silex\\Application), 'lf-lexicon', 'sense-image')\n#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(144): call_user_func_array(Array, Array)\n#10 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(64): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#11 /var/www/html/vendor/silex/silex/src/Silex/Application.php(586): Symfony\\Component\\HttpKernel
\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#12 /var/www/html/vendor/silex/silex/src/Silex/Application.php(563): Silex\\Application->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 /var/www/html/index.php(258): Silex\\Application->run()\n#14 {main}\n, referer: https://qa.languageforge.org/app/lexicon/60c114a487396d777b250e22
```

**Comment by longrunningprocess** [comment]
it turned out to be an issue with the way k8s handles folder permissions within the container.  Before the volume was mounted , the assets folder was owned by `www-data` (this is done in the Dockerfile).  But once the volume in k8s is mounted, the folder changed to `root` so an extra config is required in `docker/deployment/app-deployment.yaml` to ensure `www-data` retains ownership of that mounted folder.
